using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SmartMedical.Business.Interfaces;
using SmartMedical.Core.Entities.AIAssistant;
using SmartMedical.Core.Interfaces;

namespace SmartMedical.Business.Services
{
    public class ConversationService : IConversationService
    {
        private readonly IConversationRepository _conversationRepository;

        public ConversationService(IConversationRepository conversationRepository)
        {
            _conversationRepository = conversationRepository;
        }

        public async Task<IEnumerable<Conversation>> GetConversationsAsync(Guid userId, string search = null)
        {
            return await _conversationRepository.GetConversationsAsync(userId, search);
        }

        public async Task<Conversation> GetConversationByIdAsync(Guid id, Guid userId)
        {
            return await _conversationRepository.GetConversationByIdAsync(id, userId);
        }

        public async Task<Conversation> CreateConversationAsync(Conversation conversation)
        {
            // Generate a title based on the initial message if available
            if (string.IsNullOrEmpty(conversation.Title) && conversation.Messages?.Any() == true)
            {
                var initialMessage = conversation.Messages.FirstOrDefault();
                if (initialMessage != null)
                {
                    // Truncate the message content to create a title
                    conversation.Title = initialMessage.Content.Length > 50 
                        ? initialMessage.Content.Substring(0, 47) + "..." 
                        : initialMessage.Content;
                }
                else
                {
                    conversation.Title = "New Conversation";
                }
            }
            else if (string.IsNullOrEmpty(conversation.Title))
            {
                conversation.Title = "New Conversation";
            }

            return await _conversationRepository.CreateConversationAsync(conversation);
        }

        public async Task<Conversation> UpdateConversationAsync(Conversation conversation)
        {
            var existingConversation = await _conversationRepository.GetConversationByIdAsync(conversation.Id, conversation.UserId);
            if (existingConversation == null)
            {
                throw new KeyNotFoundException($"Conversation with ID {conversation.Id} not found");
            }

            return await _conversationRepository.UpdateConversationAsync(conversation);
        }

        public async Task<bool> DeleteConversationAsync(Guid id, Guid userId)
        {
            return await _conversationRepository.DeleteConversationAsync(id, userId);
        }

        public async Task<IEnumerable<Message>> GetMessagesAsync(Guid conversationId, int limit = 50, int offset = 0)
        {
            return await _conversationRepository.GetMessagesAsync(conversationId, limit, offset);
        }

        public async Task<Message> CreateUserMessageAsync(Guid conversationId, string content)
        {
            var message = new Message
            {
                ConversationId = conversationId,
                Role = "user",
                Content = content
            };

            return await _conversationRepository.CreateMessageAsync(message);
        }

        public async Task<Message> CreateAssistantMessageAsync(Guid conversationId, string content)
        {
            var message = new Message
            {
                ConversationId = conversationId,
                Role = "assistant",
                Content = content
            };

            return await _conversationRepository.CreateAssistantMessageAsync(message);
        }

        public async Task<(string answer, IEnumerable<string> sources)> AskHealthQuestionAsync(Guid userId, string question, bool includePersonalContext = true)
        {
            // In a real implementation, this would call an AI service to process the health question
            // For now, we'll create a conversation and return a placeholder response
            
            var conversation = new Conversation
            {
                UserId = userId,
                Title = question.Length > 50 ? question.Substring(0, 47) + "..." : question
            };
            
            var createdConversation = await _conversationRepository.CreateConversationAsync(conversation);
            
            // Create user message
            await CreateUserMessageAsync(createdConversation.Id, question);
            
            // Create assistant response
            var answer = "This is a placeholder response to your health question. In a real implementation, this would be generated by an AI service.";
            await CreateAssistantMessageAsync(createdConversation.Id, answer);
            
            // Return the answer and placeholder sources
            var sources = new List<string> { "Medical knowledge database", "Clinical guidelines" };
            
            return (answer, sources);
        }

        public async Task<(string assessment, IEnumerable<string> recommendations)> PerformSymptomAssessmentAsync(
            Guid userId, 
            string primarySymptom, 
            IEnumerable<string> additionalSymptoms, 
            string symptomDuration, 
            string symptomSeverity)
        {
            // In a real implementation, this would call an AI service to process the symptom assessment
            // For now, we'll create a conversation and return a placeholder response
            
            var symptomDescription = $"Primary: {primarySymptom}, Additional: {string.Join(", ", additionalSymptoms)}, Duration: {symptomDuration}, Severity: {symptomSeverity}";
            
            var conversation = new Conversation
            {
                UserId = userId,
                Title = $"Symptom Assessment: {primarySymptom}"
            };
            
            var createdConversation = await _conversationRepository.CreateConversationAsync(conversation);
            
            // Create user message
            await CreateUserMessageAsync(createdConversation.Id, symptomDescription);
            
            // Create assistant response
            var assessment = "This is a placeholder symptom assessment. In a real implementation, this would be generated by an AI service based on the symptoms provided.";
            await CreateAssistantMessageAsync(createdConversation.Id, assessment);
            
            // Return the assessment and placeholder recommendations
            var recommendations = new List<string> 
            { 
                "Rest and stay hydrated", 
                "Consider over-the-counter pain relievers if appropriate",
                "Consult with a healthcare provider if symptoms worsen or persist"
            };
            
            return (assessment, recommendations);
        }
    }
}
